Buy = Summon
Unit type = Unit Class
Diplomatic Marriage ([amount] Gold) = Religious Conversion ([amount] Gold)
We have married into the ruling family of [civName], bringing them under our control. = We have convinced the ruling family of [civName] to convert to our religion, bringing them under our control.
Eras = Ages
Enables construction of Spaceship parts = Enables construction of Elementalists

Use default promotions = Use default skills
Default promotions for [unitName] = Default skills for [unitName]
Promotion = Skill
Promotions =  Skills
Promote = Acquire skill
Automated units choose promotions = Automated units choose skills
Free promotion: = Free skills:
Free promotions: = Free skills:
Pick promotion = Pick skill
[unitFilter] units gain the [promotion] promotion = [unitFilter] units gain the [promotion] skill
All newly-trained [baseUnitFilter] units [cityFilter] receive the [promotion] promotion = All newly-trained [baseUnitFilter] units [cityFilter] receive the [promotion] skill
[relativeAmount]% XP required for promotions = [relativeAmount]% XP required for skills
removing the [promotion] promotion/status = removing the [promotion] skill/status
This Promotion is free = This Skill is free
[unitTriggerTarget] gains the [promotion] promotion = [unitTriggerTarget] gains the [promotion] skill
[unitTriggerTarget] loses the [promotion] promotion = [unitTriggerTarget] loses the [promotion] skill
upon gaining the [promotion] promotion = upon gaining the [promotion] skill
upon losing the [promotion] promotion = upon losing the [promotion] skill
Doing so will consume this opportunity to choose a Promotion = Doing so will consume this opportunity to choose a Skill

Barbarians = Monsters
Barbarian = Monster
Clear Barbarian Camp = Clear a Dungeon
We feel threatened by a Barbarian Camp near our city. Please take care of it. = We feel exhausted trying to clear the dungeon near our city. Please take care of it.
You find evidence of Barbarian activity. Nearby Barbarian camps are revealed! = You find evidence of a Dungeon formation!
reveal nearby Barbarian camps = reveal nearby Dungeon
Barbarian encampment = Dungeon
Home to uncivilized barbarians, will spawn a hostile unit from time to time = "Home to monsters and mythical beasts, will spawn a hostile unit from time to time and grants a random bonus when cleared.
You have encountered a barbarian unit!\nBarbarians attack everyone indiscriminately, so don't let your \n  civilian units go near them, and be careful of your scout! = You have encountered a monster!\nMonsters attack everyone indiscriminately, so don't let your \n  civilian units go near them, and be careful of your scout!
[cityState] is being invaded by Barbarians! Destroy Barbarians near their territory to earn Influence. = [cityState] is being invaded by Monsters! Slay monsters near their territory to earn Influence.
[cityState] is grateful that you killed a Barbarian that was threatening them! = [cityState] is grateful that you killed a Monster that was threatening them!
No Barbarians = No Monsters
Raging Barbarians = Raging Monsters
We have captured a barbarian encampment and recovered [goldAmount] gold! = We have cleared a dungeon!
A barbarian [unitType] has joined us! = A monster [unitType] has joined us!
A new barbarian encampment has spawned! = A new dungeon has formed!
Receive triple Gold from Barbarian encampments and pillaging Cities = Receive triple Gold from dungeon and pillaging Cities
Barbarians raided [cityName] and stole [amount] Gold from your treasury! = Monsters raided [cityName] and stole [amount] Gold from your treasury!
Cannot gain more XP from Barbarians = Cannot gain more XP from Monsters
Bonus vs. Barbarians = Bonus vs. Monsters
Barbarian spawning delay = Monster spawning delay
Turns until barbarians enter player tiles = Turns until monsters enter player tiles
Gold reward for clearing barbarian camps = Gold reward for clearing a Dungeon
Barbarian spawn modifier: [amount]%† = Monster spawn modifier: [amount]%†
Notified of new Barbarian encampments = Notified of new Dungeon
Receive [relativeAmount]% Gold from Barbarian encampments and pillaging Cities = Receive [relativeAmount]% Gold from Dungeon and pillaging Cities
When conquering an encampment, earn [amount] Gold and recruit a Barbarian unit = When conquering a Dungeon, earn [amount] Gold and recruit a Monster unit

Rain Worker = Worker

Spaceship parts remaining = Elementalists remaining
spaceship parts = elementalists
The Spaceship = Heavenly Nature
Spaceship part = Elementalist

Units that enter combat gain experience, which can then be used on promotions for that unit.\nUnits gain more experience when in Melee combat than Ranged, and more when attacking than when defending. = Units that enter combat gain experience, which can then be used on acquiring skills for that unit.\nUnits gain more experience when in Melee combat than Ranged, and more when attacking than when defending.
Units can only gain up to 30 XP from Barbarian units - meaning up to 2 promotions. After that, Barbarian units will provide no experience. = Units can only gain up to 300 XP from Barbarian units - meaning up to 8 skills. After that, Barbarian units will provide no experience.
Unit and cities are worn down by combat, which is affected by a number of different values.\nEach unit has a certain 'base' combat value, which can be improved by certain conditions, promotions and locations. = Unit and cities are worn down by combat, which is affected by a number of different values.\nEach unit has a certain 'base' combat value, which can be improved by certain conditions, skills and locations.